baseURL = 'https://amy.kmprt.nl/'
DefaultContentLanguage = "nl"
languageCode = 'nl'
title = 'Portfolio Amy Kampert'
theme = 'lightbi'

[Author]
    name = 'Amy'

[Params]
    hideAuthor = true
    selfHosted = true
    previewCardImagePlacement = "top"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
