baseURL = 'https://amy.kmprt.nl/'
DefaultContentLanguage = "nl"
languageCode = 'nl'
title = 'Portfolio Amy Kampert'
theme = 'lightbi'

[Params]
    hideAuthor = true
    selfHosted = true
    previewCardImagePlacement = "top"
    showRelatedPosts = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    name = "Over mij"
    url = "/about/"
    weight = 3

[privacy]
    [privacy.youtube]
        privacyEnhanced = true